platform:
  os: linux
  arch: arm
kind: pipeline
type: docker
name: default-test

steps:
- name: Test
  image: golang:1.15
  commands:
  - go get -u github.com/gobuffalo/packr/v2/packr2
  - make test

---
platform:
  os: linux
  arch: arm
kind: pipeline
type: docker
name: build-and-deploy

steps:
- name: test
  image: golang:1.15
  commands:
  - make test
- name: build
  image: golang:1.15
  commands:
  - go get -u github.com/gobuffalo/packr/v2/packr2
  - go install github.com/gobuffalo/packr/v2/packr2
  - GOOS=linux GOARCH=amd64 make dist/maske-auf
- name: copy binary to uberspace
  image: appleboy/drone-scp
  settings:
    host: tillk.uber.space
    username: tillk
    target: /home/tillk/bin/
    source:
    - dist/maske-auf
    strip_components: 1
    rm: false
    key:
      from_secret: uberspace_key
- name: Restart service
  image: appleboy/drone-ssh
  settings:
    host: tillk.uber.space
    username: tillk
    key:
      from_secret: uberspace_key
    script:
      - supervisorctl restart maske-auf
- name: release on codeberg
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: codeberg_api_key
    base_url: https://codeberg.org
    files: dist/*
  when:
    event:
    - tag

trigger:
  branch:
  - main
  event:
    exclude:
    - pull_request

